baseURL = 'zeeshanthedev.vercel.app'
languageCode = 'en-us'
title = 'Zeeshan Khalid'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
# googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'dark'
colorPalette = 'catpuccin'

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I'm Zeeshan Khalid, a student and aspiring developer from Pakistan. Currently, I'm pursuing my A-levels with a focus on computer science and dreaming of a future at MIT. Beyond coding, I'm deeply fascinated by the art of storytelling through filmmaking and photography. I aim to merge technical expertise with creative expression, creating impactful projects that resonate with audiences. Join me on my journey as I document my progress through devlogs, vlogs, and more.
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true


[[params.social]]
name = "github"
url = "https://github.com/zeeshanthedev590"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"


# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"